# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ContactBook.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_ContactBook(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 661)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1036, 661))
        self.background.setStyleSheet("")
        self.background.setInputMethodHints(QtCore.Qt.ImhNone)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("PVS/Background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.BackgroundBehind_2 = QtWidgets.QLabel(self.centralwidget)
        self.BackgroundBehind_2.setEnabled(True)
        self.BackgroundBehind_2.setGeometry(QtCore.QRect(15, 15, 1006, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BackgroundBehind_2.sizePolicy().hasHeightForWidth())
        self.BackgroundBehind_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.BackgroundBehind_2.setFont(font)
        self.BackgroundBehind_2.setToolTipDuration(0)
        self.BackgroundBehind_2.setAutoFillBackground(False)
        self.BackgroundBehind_2.setStyleSheet("background: rgba(35, 35, 35, 0.7);\n"
                                              "border-radius:5px;\n"
                                              "")
        self.BackgroundBehind_2.setInputMethodHints(
            QtCore.Qt.ImhNoPredictiveText)
        self.BackgroundBehind_2.setText("")
        self.BackgroundBehind_2.setAlignment(QtCore.Qt.AlignCenter)
        self.BackgroundBehind_2.setObjectName("BackgroundBehind_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(915, 15, 106, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.help_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.help_btn.setMinimumSize(QtCore.QSize(18, 18))
        self.help_btn.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.help_btn.setFont(font)
        self.help_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_btn.setStyleSheet("background-color: rgb(5,195,221);\n"
                                    "border-radius:8px;")
        self.help_btn.setObjectName("help_btn")
        self.horizontalLayout.addWidget(self.help_btn)
        self.pushButtonMinimize = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonMinimize.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMinimize.setStyleSheet("background-color: rgb(0, 255, 0);\n"
                                              "border-radius:8px;")
        self.pushButtonMinimize.setText("")
        self.pushButtonMinimize.setObjectName("pushButtonMinimize")
        self.horizontalLayout.addWidget(self.pushButtonMinimize)
        self.pushButtonMaximiz = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonMaximiz.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonMaximiz.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonMaximiz.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMaximiz.setStyleSheet("background-color: rgb(255, 226, 0);\n"
                                             "border-radius:8px;")
        self.pushButtonMaximiz.setText("")
        self.pushButtonMaximiz.setObjectName("pushButtonMaximiz")
        self.horizontalLayout.addWidget(self.pushButtonMaximiz)
        self.pushButtonExit = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonExit.setStyleSheet("background-color:rgb(255, 97, 6);\n"
                                          "border-radius:8px;")
        self.pushButtonExit.setText("")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.horizontalLayout.addWidget(self.pushButtonExit)
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(330, 60, 301, 46))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.name.setFont(font)
        self.name.setAutoFillBackground(False)
        self.name.setStyleSheet("background: rgba(0, 0, 0,150);\n"
                                "color : rgba(220, 220,220);\n"
                                "padding-left: 10;\n"
                                "border-radius:4px;\n"
                                "")
        self.name.setText("")
        self.name.setCursorPosition(0)
        self.name.setAlignment(QtCore.Qt.AlignLeading |
                               QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.name.setClearButtonEnabled(False)
        self.name.setObjectName("name")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(15, 120, 301, 46))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.email.setFont(font)
        self.email.setAutoFillBackground(False)
        self.email.setStyleSheet("background: rgba(0, 0, 0,150);\n"
                                 "color : rgba(220, 220,220);\n"
                                 "padding-left: 10;\n"
                                 "border-radius:4px;\n"
                                 "")
        self.email.setText("")
        self.email.setCursorPosition(0)
        self.email.setAlignment(QtCore.Qt.AlignLeading |
                                QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.email.setClearButtonEnabled(False)
        self.email.setObjectName("email")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(15, 270, 1006, 331))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setAcceptDrops(False)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("background: rgba(220, 220, 220,220);\n"
                                       "gridline-color: rgb(255, 255, 255);")
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(2)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed |
                                         QtWidgets.QAbstractItemView.DoubleClicked | QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setDragDropMode(
            QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectColumns)
        self.tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(80)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(0)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.phone = QtWidgets.QLineEdit(self.centralwidget)
        self.phone.setGeometry(QtCore.QRect(330, 120, 301, 46))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.phone.setFont(font)
        self.phone.setAutoFillBackground(False)
        self.phone.setStyleSheet("background: rgba(0, 0, 0,150);\n"
                                 "color : rgba(220, 220,220);\n"
                                 "padding-left: 10;\n"
                                 "border-radius:4px;\n"
                                 "")
        self.phone.setText("")
        self.phone.setCursorPosition(0)
        self.phone.setAlignment(QtCore.Qt.AlignLeading |
                                QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.phone.setClearButtonEnabled(False)
        self.phone.setObjectName("phone")
        self.ID = QtWidgets.QLineEdit(self.centralwidget)
        self.ID.setGeometry(QtCore.QRect(15, 60, 301, 46))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.ID.setFont(font)
        self.ID.setAutoFillBackground(False)
        self.ID.setStyleSheet("background: rgba(0, 0, 0,150);\n"
                              "color : rgba(220, 220,220);\n"
                              "padding-left: 10;\n"
                              "border-radius:4px;\n"
                              "")
        self.ID.setText("")
        self.ID.setCursorPosition(0)
        self.ID.setAlignment(QtCore.Qt.AlignLeading |
                             QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.ID.setClearButtonEnabled(False)
        self.ID.setObjectName("ID")
        self.insert = QtWidgets.QPushButton(self.centralwidget)
        self.insert.setGeometry(QtCore.QRect(30, 195, 136, 46))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.insert.sizePolicy().hasHeightForWidth())
        self.insert.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.insert.setFont(font)
        self.insert.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.insert.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#e65c00, stop:1 #ffaf19);\n"
                                  "color : rgba(0, 0,0);\n"
                                  "border-radius:4px;\n"
                                  "\n"
                                  "")
        self.insert.setObjectName("insert")
        self.deletee = QtWidgets.QPushButton(self.centralwidget)
        self.deletee.setGeometry(QtCore.QRect(330, 195, 136, 46))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.deletee.sizePolicy().hasHeightForWidth())
        self.deletee.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.deletee.setFont(font)
        self.deletee.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deletee.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#fdfc47, stop:1 #24fe41);\n"
                                   "color : rgba(0, 0,0);\n"
                                   "border-radius:4px;\n"
                                   "\n"
                                   "")
        self.deletee.setObjectName("deletee")
        self.update = QtWidgets.QPushButton(self.centralwidget)
        self.update.setGeometry(QtCore.QRect(180, 195, 136, 46))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.update.sizePolicy().hasHeightForWidth())
        self.update.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.update.setFont(font)
        self.update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);\n"
                                  "color : rgba(0, 0,0);\n"
                                  "border-radius:4px;\n"
                                  "\n"
                                  "")
        self.update.setObjectName("update")
        self.search = QtWidgets.QLineEdit(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(630, 195, 271, 46))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.search.setFont(font)
        self.search.setAutoFillBackground(False)
        self.search.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffffff, stop:1 #abbaab);\n"
                                  "\n"
                                  "color : rgba(0, 0,0);\n"
                                  "padding-left: 10;\n"
                                  "border-radius:4px;\n"
                                  "\n"
                                  "\n"
                                  "\n"
                                  "")
        self.search.setText("")
        self.search.setCursorPosition(0)
        self.search.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.search.setClearButtonEnabled(False)
        self.search.setObjectName("search")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(480, 195, 136, 46))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.clear.setFont(font)
        self.clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #5488ff,stop:1 #a5fecb);\n"
                                 "color : rgba(0, 0,0);\n"
                                 "border-radius:4px;\n"
                                 "\n"
                                 "")
        self.clear.setObjectName("clear")
        self.line_2 = QtWidgets.QLabel(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(15, 180, 1006, 76))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("background: rgba(0, 0, 0,150);\n"
                                  "color : rgba(220, 220,220);\n"
                                  "border-radius:4px;\n"
                                  "\n"
                                  "\n"
                                  "")
        self.line_2.setText("")
        self.line_2.setTextFormat(QtCore.Qt.AutoText)
        self.line_2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_2.setObjectName("line_2")
        self.searchbyname = QtWidgets.QRadioButton(self.centralwidget)
        self.searchbyname.setGeometry(QtCore.QRect(915, 195, 91, 20))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.searchbyname.setFont(font)
        self.searchbyname.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffffff, stop:1 #abbaab);\n"
                                        "\n"
                                        "color : rgba(0, 0,0);\n"
                                        "padding-left: 10;\n"
                                        "border-radius:4px;\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "")
        self.searchbyname.setChecked(True)
        self.searchbyname.setObjectName("searchbyname")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.searchbyname)
        self.searchbyid = QtWidgets.QRadioButton(self.centralwidget)
        self.searchbyid.setGeometry(QtCore.QRect(915, 220, 91, 20))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.searchbyid.setFont(font)
        self.searchbyid.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffffff, stop:1 #abbaab);\n"
                                      "\n"
                                      "color : rgba(0, 0,0);\n"
                                      "padding-left: 10;\n"
                                      "border-radius:4px;\n"
                                      "\n"
                                      "\n"
                                      "\n"
                                      "")
        self.searchbyid.setObjectName("searchbyid")
        self.buttonGroup.addButton(self.searchbyid)
        self.address = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(645, 60, 376, 106))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.address.setFont(font)
        self.address.setStyleSheet("background: rgba(0, 0, 0,150);\n"
                                   "color : rgba(220, 220,220);\n"
                                   "padding-top: 7;\n"
                                   "padding-left: 10;\n"
                                   "padding-right: 10;\n"
                                   "border-radius:4px;\n"
                                   "")
        self.address.setObjectName("address")
        self.refresh = QtWidgets.QPushButton(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(15, 615, 1006, 30))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.refresh.sizePolicy().hasHeightForWidth())
        self.refresh.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.refresh.setFont(font)
        self.refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #E100FF,stop:1 #4A00E0);\n"
                                   "color : rgba(0, 0,0);\n"
                                   "border-radius:4px;\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "\n"
                                   "")
        self.refresh.setObjectName("refresh")
        self.background.raise_()
        self.line_2.raise_()
        self.BackgroundBehind_2.raise_()
        self.layoutWidget.raise_()
        self.name.raise_()
        self.email.raise_()
        self.tableWidget.raise_()
        self.phone.raise_()
        self.ID.raise_()
        self.insert.raise_()
        self.deletee.raise_()
        self.update.raise_()
        self.search.raise_()
        self.clear.raise_()
        self.searchbyname.raise_()
        self.searchbyid.raise_()
        self.address.raise_()
        self.refresh.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButtonExit.clicked.connect(MainWindow.close)
        self.pushButtonMinimize.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.help_btn.setText(_translate("MainWindow", "H"))
        self.name.setPlaceholderText(_translate("MainWindow", "Name"))
        self.email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Phone Number"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Address"))
        self.phone.setPlaceholderText(_translate("MainWindow", "Phone Number"))
        self.ID.setPlaceholderText(_translate("MainWindow", "ID"))
        self.insert.setText(_translate("MainWindow", "INSERT "))
        self.deletee.setText(_translate("MainWindow", "DELETE "))
        self.update.setText(_translate("MainWindow", "UPDATE "))
        self.search.setPlaceholderText(
            _translate("MainWindow", "Search by Name/ID"))
        self.clear.setText(_translate("MainWindow", "CLEAR"))
        self.searchbyname.setText(_translate("MainWindow", "Name"))
        self.searchbyid.setText(_translate("MainWindow", "ID"))
        self.address.setPlaceholderText(_translate("MainWindow", "Address"))
        self.refresh.setText(_translate("MainWindow", "Refresh Table"))
